#!/bin/bash

mod_mem () {
  # Customizable configuration constants
  local -r DEFAULT_PRE='ﱨ  '
  local -r DEFAULT_SUF='GiB'

  local -r pre="${1-${DEFAULT_PRE}}"
  local -r suf="${2-${DEFAULT_SUF}}"

  printf '%b' "${pre}"
  #free | awk 'NR == 2 {printf "%3.0f", $3 * 100 / $2}'
  free | awk 'NR == 2 {printf "%.3f", $3 / (1024*1024)}'
  printf ' %b' "${suf}"
}


case $BLOCK_BUTTON in
	1) notify-send -a "" "Memory Hogs" "$(ps axch -o cmd:15,%mem --sort=-%mem | head)" ;;
	3) 
        notify-send -a "" "Memory Module" "Toggling htop..."
        pidof htop && pkill htop || /bin/sh -c "st htop" 
        ;;
esac

mod_mem
